### ISSUE TITLE
'NoneType' object has no attribute 'expand' when using backbone dpt

### ISSUE THREAD

**Issue by jackonealll** [fupiao1998/TrasformerSOD#1]
Hello, thank you for sharing your excellent work.

I am facing this error when running your code in a custom dataset. This error occur specifically when using `--backbone dpt`. When using `--backbone R50` works properly. 

Could you please help me?

```
$ python train.py --task lesions --uncer_method basic --backbone dpt --use_22k
[INFO] Experiments saved in:  lesions_2.5e-05_dpt_basic_cat_basic_REMOVE
[INFO]: Model based on [dpt_basic_cat_basic] have 108.2544Mb paramerters in total
dataset_size 27508
Learning Rate: 2.50e-05
Epoch[001/050]:   0%|                                                                                                                                                                                                 | 0/2299 [00:00<?, ?it/s]/home/viplabgpu/anaconda3/envs/gpu/lib/python3.9/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Epoch[001/050]:   0%|                                                                                                                                                                                                 | 0/2299 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/TrasformerSOD/train.py", line 43, in <module>
    model_dict, loss_record = train_one_epoch(epoch, model_list, optimizer_list, train_loader, dataset_size, loss_fun)
  File "/home/TrasformerSOD/trainer/trainer_basic.py", line 43, in train_one_epoch
    pred = generator(img=images, depth=depth)
  File "/home/viplabgpu/anaconda3/envs/gpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/TrasformerSOD/model/saliency_detector.py", line 34, in forward
    backbone_features = self.backbone(img)
  File "/home/viplabgpu/anaconda3/envs/gpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/TrasformerSOD/model/backbone/DPT.py", line 83, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "/home/TrasformerSOD/model/backbone/DPT_blocks/vit.py", line 107, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "/home/TrasformerSOD/model/backbone/DPT_blocks/vit.py", line 185, in forward_flex
    dist_token = self.dist_token.expand(B, -1, -1)
AttributeError: 'NoneType' object has no attribute 'expand'
```

**Comment by MaoYuxin25** [comment]
hello, maybe you need to keep the timm version the same as the DPT repo.
